# Generated by Django 4.2.13 on 2024-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
