# Generated by Django 4.2.13 on 2024-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_content_bg_projects_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
