# Generated by Django 4.2.13 on 2024-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='company_name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
