# Generated by Django 4.2.13 on 2024-06-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partners_company_name_bg_partners_company_name_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='company_name_de',
            new_name='company_name_ru',
        ),
    ]
