# Generated by Django 4.2.13 on 2024-06-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_company_name_de_partners_company_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='company_name_en',
        ),
    ]
