# Generated by Django 4.2.13 on 2024-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_remove_partners_company_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
