# Generated by Django 4.2.13 on 2024-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
