# Generated by Django 4.2.13 on 2024-06-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_content_bg_services_content_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='content_de',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='title_de',
            new_name='title_ru',
        ),
    ]
