# Generated by Django 4.2.13 on 2024-06-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_content_de_services_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title_en',
        ),
    ]
